name: Liquibase Update

inputs:
  URL:
    required: true
  PASSWORD:
    required: true
  USER:
    required: true
  DRIVER:
    required: false
  changelogFile:
    description: 'Name of the changelog file with extension'
    required: false

  runs:
    using: 'composite'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      generateMatrix: ${{ steps.check-changelog.outputs.generateMatrix }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if changelogFile is empty
        id: check-changelog
        run: |
          if [[ -z "${{ inputs.changelogFile }}" ]]; then
            echo "::set-output name=generateMatrix::true"
          else
          echo "::set-output name=generateMatrix::false"
          fi
        shell: bash

      - name: Run update
        uses: liquibase-github-actions/update@v4.23.2
        if: steps.check-changelog.outputs.generateMatrix == 'false'
        with:
          changelogFile: ${{ inputs.changelogFile }}
          url: ${{ inputs.URL }}
          driver: ${{ inputs.DRIVER }}     
          password: ${{ inputs.PASSWORD }}
          username: ${{ inputs.USER }}
          logLevel: INFO


      - name: Generate Matrix
        id: set-matrix
        if: steps.check-changelog.outputs.generateMatrix == 'true'
        run: |
          # Replace with your actual Liquibase update command
          changelogFile="${{ github.event.inputs.changelogFile }}"
          url="${{ github.event.inputs.URL }}"
          username="${{ github.event.inputs.USER }}"
          password="${{ github.event.inputs.PASSWORD }}"

          liquibase --changeLogFile="$changelogFile" \
                    --url="$url" \
                    --username="$username" \
                    --password="$password" \
                    update