name: Liquibase Update

on:
    workflow_dispatch:

jobs:
  liquibase_update:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: liquibase-github-actions/status@v4.23.2
          with:
            # The root changelog
            # string
            # Required
            changelogFile: ${{ secrets.LB_DEVOPS_CHANGELOGFILE }}
        
            # The JDBC database connection URL
            # string
            # Required
            url: ${{ secrets.LB_DEVOPS_URL }}
        
 
        
            # Changeset contexts to match
            # string
            # Optional
            contextFilter: ""
        
            # The default catalog name to use for the database connection
            # string
            # Optional
            defaultCatalogName: ""
        
            # The default schema name to use for the database connection
            # string
            # Optional
            defaultSchemaName: ""
        
            # The JDBC driver class
            # string
            # Optional
            driver: ${{ secrets.LB_DEVOPS_DRIVER }}
        
            # The JDBC driver properties file
            # string
            # Optional
            driverPropertiesFile: ""
        
            # Changeset labels to match
            # string
            # Optional
            labelFilter: ""
        
            # Password to use to connect to the database
            # string
            # Optional
            password: ${{ secrets.LB_DEVOPS_PASSWORD }}
        
      
        
            # Username to use to connect to the database
            # string
            # Optional
            username: ${{ secrets.LB_DEVOPS_USER }}

            logLevel: DEBUG
        
        