name: Liquibase Update

on:
  workflow_dispatch:

jobs:
  liquibase_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/generate-changelog@v4.23.2
        with:
          changelogFile: ${{ secrets.LB_DEVOPS_CHANGELOGFILE }}
          url: ${{ secrets.LB_DEVOPS_URL }}
          defaultCatalogName: ""
          defaultSchemaName: ""
          driver: ${{ secrets.LB_DEVOPS_DRIVER }}
          driverPropertiesFile: ""
          password: ${{ secrets.LB_DEVOPS_PASSWORD }}
          username: ${{ secrets.LB_DEVOPS_USER }}
          logLevel: INFO

      # Commit and push the updated file
      - name: Commit and Push Liquibase Output
        run: |
          git config --local user.email "thalisson1980@gmail.com"
          git config --local user.name "thalisson1980"
          git commit -m "Update Liquibase output"
          git push
