name: Liquibase Update

on:
    workflow_dispatch:

jobs:
  liquibase_update:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: liquibase-github-actions/update@v4.23.2
          with:
            # The root changelog
            # string
            # Required
            changelogFile: ${{ secrets.LB_DEVOPS_CHANGELOGFILE }}
        
            # The JDBC database connection URL
            # string
            # Required
            url: ${{ secrets.LB_DEVOPS_URL }}