name : update 

on:
    workflow_dispatch:
        inputs:
         changelogFile:
            required: false

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@main

    - name: update
      uses: thalisson1980/liquibase/.github/actions/update@main
      with:
        changelogFile: ${{inputs.changelogFile}}
        URL: ${{secrets.LB_DEVOPS_URL}}
        DRIVER: ${{secrets.LB_DEVOPS_DRIVER}}
        PASSWORD: ${{secrets.LB_DEVOPS_PASSWORD}}
        USER: ${{secrets.LB_DEVOPS_USER}}
          
        