name: Liquibase Update All

on:
  workflow_dispatch:

jobs:
  liquibase_update_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Liquibase updates
        run: |
           python .github/actions/src/updateAll.py
        env:
         lb_devops_url: ${{ secrets.LB_DEVOPS_URL }}
         lb_devops_password: ${{ secrets.LB_DEVOPS_PASSWORD }}
         lb_devops_user: ${{ secrets.LB_DEVOPS_USER }}
