name : update 

on:
    workflow_dispatch:
        inputs:
         changelogFile:
            required: false

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@main

    - name: php
      uses: thalisson1980/liquibase/.github/actions/update@main
      with:
        changelogFile: ${{inputs.changelogFile}}
          
        