name: Liquibase Update

on:
  workflow_dispatch:

    inputs:
      changelog_file:
        description: 'Name of the changelog file, if empty runs all files'
        required: false
      url:
        required: true
      user:
        required: true
      password:
        required: true
      driver:
        required: false

jobs:
  update_one:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      generate_matrix: ${{ steps.check-changelog.outputs.generate_matrix }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if changelogFile is empty
        id: check-changelog
        run: |
          if [[ -z "${{ github.event.inputs.changelog_file }}" ]]; then
            echo "generate_matrix=true" >> $GITHUB_OUTPUT
          else
          echo "generate_matrix=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Run update
        uses: liquibase-github-actions/update@v4.23.2
        if: steps.check-changelog.outputs.generate_matrix == 'false'
        with:
          changelogFile: migrations/${{ github.event.inputs.changelog_file }}.sql
          url: ${{ github.event.inputs.url }}
          driver: ${{ github.event.inputs.driver }}     
          password: ${{ github.event.inputs.password }}
          username: ${{ github.event.inputs.user }}
          logLevel: INFO


      - name: Generate Matrix
        id: set-matrix
        if: steps.check-changelog.outputs.generate_matrix == 'true'
        run: |
          # Generate the matrix in JSON format
          matrix_string="["
          first=true
          for file in $(find migrations -type f); do
            if [ "$first" = false ]; then
              matrix_string="${matrix_string},"
            fi
            matrix_string="${matrix_string}\"$file\""
            first=false
          done
          matrix_string="${matrix_string}]"
          echo "matrix=$matrix_string" >> $GITHUB_OUTPUT
          echo "$matrix_string"
        shell: bash


  update_all:
    needs: update_one
    runs-on: ubuntu-latest
    if: needs.update_one.outputs.generate_matrix == 'true'
    strategy:
      matrix:
        files: ${{fromJson(needs.update_one.outputs.matrix)}}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run update
        uses: liquibase-github-actions/update@v4.23.2
        with:
          changelogFile: ${{ matrix.files }}
          url: ${{ github.event.inputs.url }}
          driver: ${{ github.event.inputs.driver }}     
          password: ${{ github.event.inputs.password }}
          username: ${{ github.event.inputs.user }}
          logLevel: INFO