name: Liquibase Update All

on:
  workflow_dispatch:

jobs:
  liquibase_update_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List changelog files
        run: |
          changelog_folder="migrations"
          for file in $changelog_folder/*.sql; do
            echo "Found changelog file: $file"
            # Run the Liquibase update action for each changelog file
            echo "::set-output name=changelogFile::$file"
          done
        id: list_changelogs

      - name: Run Liquibase updates
        run: |
          changelog_files=($(echo "${{ steps.list_changelogs.outputs.changelogFile }}" | tr '\n' ' '))
          for changelog_file in "${changelog_files[@]}"; do
            echo "Running Liquibase update for $changelog_file"
            
            # Use the public Liquibase update action for each changelog file
            # Pass the changelog file path as an input to the action
            echo "::set-env name=CHANGELOG_FILE::$changelog_file"
            uses: liquibase-github-actions/update@v4.23.2
              with:
                changelogFile: ${{ env.CHANGELOG_FILE }}
                url: ${{ secrets.LB_DEVOPS_URL }}
                driver: ${{ secrets.LB_DEVOPS_DRIVER }}
                username: ${{ secrets.LB_DEVOPS_USER }}
                password: ${{ secrets.LB_DEVOPS_PASSWORD }}
                logLevel: INFO
          done
