name: Liquibase Update All

on:
  workflow_dispatch:

jobs:
  liquibase_update:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: "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"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List migration files
        run: |
          # Find all migration files in the migrations folder and store them in an array
          migration_files=($(find migrations/ -type f -name "*.sql"))

          # Iterate through the array and trigger the Liquibase Update workflow for each file
          for file in "${migration_files[@]}"; do
            echo "Processing file: $file"
            # Extract the filename without extension
            filename=$(basename -- "$file")
            filename_without_extension="${filename%.*}"

            # Trigger the Liquibase Update workflow for this file
            echo "Triggering Liquibase Update for $filename"
            gh workflow run 70696634 -f changelogFile="$filename"
          done
        shell: bash
