name: Liquibase Update All

on:
  workflow_dispatch:

jobs:
  liquibase_update:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3


      - name: Generate Matrix
        id: generate-matrix
        run: |
          # Generate the matrix in JSON format
          matrix_string="["
          first=true
          for file in $(find migrations -type f); do
            if [ "$first" = false ]; then
              matrix_string="${matrix_string},"
            fi
            matrix_string="${matrix_string}\"$file\""
            first=false
          done
          matrix_string="${matrix_string}]"
          echo "::set-output name=matrix::$matrix_string"
        shell: bash


      - name: List migration files
        run: |
          # Find all migration files in the migrations folder and store them in an array
          migration_files=($(find migrations/ -type f -name "*.sql"))

          # Iterate through the array and trigger the Liquibase Update workflow for each file
          for file in "${migration_files[@]}"; do
            echo "Processing file: $file"
            # Extract the filename without extension
            filename=$(basename -- "$file")
            filename_without_extension="${filename%.*}"

            # Trigger the Liquibase Update workflow for this file
            echo "Triggering Liquibase Update for $filename"
            gh workflow run Liquibase_Update -f changelogFile="$filename"
          done
        shell: bash
