name: Liquibase Update All

on:
  workflow_dispatch:

jobs:
  liquibase_update_all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List changelog files
        run: |
          changelog_folder="migrations"
          for file in $changelog_folder/*.sql; do
            echo "Found changelog file: $file"
            # Run the Liquibase update action for each changelog file
            echo "::set-output name=changelogFile::$file"
          done
        id: list_changelogs

      - name: Run Liquibase updates
        run: |
           python .github/actions/src/updateAll.py
        env:
         lb_devops_url: ${{ secrets.LB_DEVOPS_URL }}
         lb_devops_password: ${{ secrets.LB_DEVOPS_PASSWORD }}
         lb_devops_username: ${{ secrets.LB_DEVOPS_USER }}
